name = "ulid-generator-mcp"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# 環境変数（必要に応じて設定）
# [vars]
# ENVIRONMENT = "production"

# カスタムドメイン（必要に応じて設定）
# [[routes]]
# pattern = "ulid-mcp.example.com/*"
# zone_name = "example.com"

# KVストレージ（将来的に状態管理が必要な場合）
# [[kv_namespaces]]
# binding = "ULID_CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"